spring:
  application:
    name: wg-server-controller
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'
    jmx:
      exposure:
        include: health